services:
  db:
    image: postgres:17
    container_name: todo_db
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: todo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://todo_user:yourpassword@db:5432/todo_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "sleep 5 && python run.py"
volumes:
  postgres_data: